# -*- coding: utf-8 -*-
"""Google Colab Tutorial 2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qi4-BRqZ3qI3x_Jtr5ci_oRvHDMQpdiW

# **Google Colab Tutorial**


Should you have any question, contact TAs via <br/> mlta-2023-spring@googlegroups.com

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>What is Colaboratory?</h1>

Colaboratory, or "Colab" for short, allows you to write and execute Python in your browser, with 
- Zero configuration required
- Free access to GPUs
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier. Watch [Introduction to Colab](https://www.youtube.com/watch?v=inN8seMm7UI) to learn more, or just get started below!

You can type python code in the code block, or use a leading exclamation mark ! to change the code block to bash environment to execute linux code.

To utilize the free GPU provided by google, click on "Runtime"(執行階段) -> "Change Runtime Type"(變更執行階段類型). There are three options under "Hardward Accelerator"(硬體加速器), select "GPU". 
* Doing this will restart the session, so make sure you change to the desired runtime before executing any code.
"""

import torch
torch.cuda.is_available() # is GPU available
# Outputs True if running with GPU

# check allocated GPU type
!nvidia-smi

"""**1. Download Files via google drive**

  A file stored in Google Drive has the following sharing **link**：

https://drive.google.com/file/d/14FK5G6DOh7EdLyoj4D5teRSzriTOUPD7/view?usp=sharing


  It is possible to download the file via Colab knowing the **link**, using the **--fuzzy** command.





"""

# Download the file with the following link,  and rename it to pikachu.png
!gdown --fuzzy https://drive.google.com/file/d/14FK5G6DOh7EdLyoj4D5teRSzriTOUPD7/view?usp=sharing --output pikachu.png

# List all the files under the working directory
!ls

"""Exclamation mark (!) starts a new shell, does the operations, and then kills that shell, while percentage (%) affects the process associated with the notebook

It can be seen that `pikachu.png` is saved the the current working directory. 

![](https://i.imgur.com/bonrOlgm.png)

The working space is temporary, once you close the browser, the files will be gone.

Double click to view image

![](https://imgur.com/MIPrdqu.png)

**2. Mounting Google Drive**

  One advantage of using google colab is that connection with other google services such as Google Drive is simple. By mounting google drive, the working files can be stored permanantly. After executing the following code block, your google drive will be mounted at `/content/drive`

![](https://i.imgur.com/IbMf5Tg.png)
"""

from google.colab import drive
drive.mount('/content/drive')

"""After mounting the drive, the content of the google drive will be mounted on a directory named `MyDrive`

![](https://i.imgur.com/jDtI10Cm.png)

After mounting the drive, all the changes will be synced with the google drive.
Since models could be quite large, make sure that your google drive has enough space.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive 
#change directory to google drive
!mkdir ML2023 #make a directory named ML2023
# %cd ./ML2023
#change directory to ML2023

"""Use bash command pwd to output the current directory"""

!pwd #output the current directory

"""Repeat the downloading process, this time, the file will be stored permanently in your google drive."""

!gdown --fuzzy https://drive.google.com/file/d/14FK5G6DOh7EdLyoj4D5teRSzriTOUPD7/view?usp=sharing --output pikachu.png

"""Check the file structure

![](https://imgur.com/ujnczAa.png)

For all the homeworks, the data can be downloaded and stored similar as demonstrated in this notebook.

# **Google Colab Advanced Tips**

## 1. GPU 選擇問題

### 🤔 Issue
由於某些 HW 可能需要 train 比較久的作業，對於 GPU 本身的要求可能比較嚴苛。 

如果直接使用 K80 可能會跑非常久⋯⋯

### 😅 Solution
使用 `nvidia-smi` 確認 GPU 的名稱，人眼確認  
如果拿到 K80 即恢復原廠設定。
"""

!nvidia-smi

"""## 2. Colab 斷線問題
### 🤔 Issue
由於 Colab 會偵測使用者是否在電腦前面使用，因此一定時間沒有動作會自動斷線

### 😅 Original Solution
開啟 F12 控制臺，貼上 Javascript  

```javascript
function ClickConnect() {
    console.log("Working...");  // debug 用
    // 去選擇按鈕
    var connectbutton = document.querySelector(
        "colab-toolbar-button" +
        "#connect-icon.big-icon.icon-okay");
    // 點個兩下
    connectbutton.click(); connectbutton.click();
};

// 設定固定每 10 分鐘點一下
const stopit = setInterval(
    ClickConnect, 10 * 60 * 1000);

// 這行沒有沒關係，只是避免停不下來
const stopping = stopper => clearInterval(stopper);
```

使得瀏覽器每 10 分鐘會自己按兩下這個按鈕  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<img src="https://i.imgur.com/Kuc4Lsz.png" />

### 😄 Another Solution 1

由於實際上網址列也可以執行 JavaScript，  
就是如果把
```javascript
console.log("Hi");
```
前面加上 `javascript:` 放在網址列變成
```
javascript:console.log("Hi");
```
就可以等效讓瀏覽器執行

只是為了安全性，通常瀏覽器會自動把 `javascript:` 截掉
***
於是，如果把一個 `j` 切掉變成 `avascript:...`   
瀏覽器就不會發現了～  
下面的 code 會產生上面那份 code 的網址列版本 

![](https://i.imgur.com/1BlLdBk.png)
"""

import IPython
from google.colab import output
from IPython.display import Markdown

# display JavaScript code
display(IPython.display.Javascript('''
  var string_to_paste = (
      "avascript:function ClickConnect() {    "
    + "console.log('Working...');     "
    + "var connectbutton = document.querySelector("
    + "        'colab-toolbar-button' +       "
    + " '#connect-icon.big-icon.icon-okay');  "
    + "  connectbutton.click();   "
    + " connectbutton.click();};"
    + "const stopit = setInterval(   "
    + " ClickConnect, 10 * 60 * 1000);"
    + "const stopper = stopper => "
    + "clearInterval(stopper);")
  window.someValue = new Promise(resolve => {
    setTimeout(() => {
      resolve(string_to_paste);
    }, 100);
  });
'''))

# remind to prepend `j`
print("\x1b[01;31m請記得要在開頭加上 \"j\" ！\x1b[0m\n")
value = output.eval_js('someValue');

# display
value

"""### 😄 Another Solution 2

```javascript
function ClickConnect() {
    console.log("Working");
    document.querySelector("colab-connect-button")
            .shadowRoot
            .getElementById("connect").click();
}

setInterval(ClickConnect, 60000);
```

那就是把整堆 code 前面加上 `avascript:`   
最後手動加上 `j`，整個貼到網址列就行了～

### 🚧 **Issues**
+ [ ] 無法防止「我不是機器人」的情況
> 如果有誰知道怎麼辦的，歡迎上 NTU COOL 分享～
+ [ ] 其他非 Chrome 瀏覽器可能需要調整程式碼，可以從 F12 處理

# Reference
This notebook uses code written by 陳建成 in 2021 and 孟妍 in 2022 and modified by 蕭淇元 and Kuang, Ming Chen in 2023
"""